# Generated by Django 5.2.9 on 2025-12-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Cargo')),
                ('company', models.CharField(max_length=100, verbose_name='Empresa')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localização')),
                ('status', models.CharField(choices=[('enviado', 'Currículo Enviado'), ('entrevista', 'Entrevista Agendada'), ('teste', 'Teste Técnico'), ('aguardando', 'Aguardando Resposta'), ('rejeitado', 'Rejeitado')], default='enviado', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True, verbose_name='Data de Aplicação')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações')),
            ],
        ),
    ]
